### ISSUE TITLE
Missing text in http://robgungor.com/tutorial/#french_Story2_57_next_abfh

### ISSUE THREAD

**Issue by MediaSmarts** [DoYourThing/CyberChoices#229]
Missing text "Comment crois-tu que Laura s'est sentie après que les choses se soient arrangées?"

![sestsentie](https://cloud.githubusercontent.com/assets/8646341/5650989/8ccb3c14-9671-11e4-9c37-c75ae4f48745.png)

**Comment by robgungor** [comment]
this also has been fixed
