### ISSUE TITLE
No graphic for http://robgungor.com/tutorial/#english_Story4_25_previous_abc

### ISSUE THREAD

**Issue by MediaSmarts** [DoYourThing/CyberChoices#230]
![nofirstpanel](https://cloud.githubusercontent.com/assets/8646341/5652759/add9b128-9681-11e4-9d7a-c212ba45ef79.png)

**Comment by jmseck** [comment]
@MediaSmarts Has this been missing all along?
@robgungor Rob do you have the graphic for this URL?

**Comment by jmseck** [comment]
@MediaSmarts @robgungor I think I see the problem, the graphic is there if you proceed. Rob please correct, thanks!

**Comment by robgungor** [comment]
how are you supposed to navigate to this page?

**Comment by MediaSmarts** [comment]
From sorting task http://robgungor.com/tutorial/#english_Story4_24_previous_ab and then 1/"Delete the Bad Stuff".
The graphic doesn't appear whether you navigate directly to this URL or get there from the sorting task, but it's present from http://robgungor.com/tutorial/#english_Story4_27_next_abc on.

**Comment by robgungor** [comment]
got it. fixed now, please verify.
