### ISSUE TITLE
Wrong text in Help box for content pages when Help icon is clicked

### ISSUE THREAD

**Issue by MediaSmarts** [DoYourThing/CyberChoices#232]
Should read:

To hear something again or go back in the story, press the left arrow on the keyboard or click the back button on the screen. Press 'r' to hear the last thing that was said again.

Pour réentendre quelque chose ou pour retourner en arrière dans l’histoire, appuie sur la touche ‘flèche gauche’ sur le clavier ou clique sur le bouton ‘Précédent’ à l’écran. Appuie sur ‘r’ pour réentendre ce qui vient d’être dit.

(Works when H is pressed. Audio is correct.)

![wrongtexthelpbuttonenglish](https://cloud.githubusercontent.com/assets/8646341/5667461/d11b3a58-9735-11e4-8226-c768e997add8.png)

![wrongtexthelpbuttonfrench](https://cloud.githubusercontent.com/assets/8646341/5667463/db21d7aa-9735-11e4-8e1b-50489f8b57b3.png)

**Comment by robgungor** [comment]
this is working for me - pls verify

**Comment by MediaSmarts** [comment]
Still seeing the wrong text when I click the Help icon. ("Click on a text box" refers to functionality that wasn't implemented.)

![clickonabox](https://cloud.githubusercontent.com/assets/8646341/6172044/7795ea18-b2ac-11e4-8f57-db8f0c3d87be.png)

**Comment by robgungor** [comment]
k, fixed for me now, pls verify.

**Comment by MediaSmarts** [comment]
Fixed -- thanks
